name: toast_badge
description: Showing Info Badge in Flutter Widgets like Toast.
version: 0.1.1
homepage: https://github.com/erluxman/toast_badge
issue_tracker: https://github.com/erluxman/toast_badge/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
